### ISSUE TITLE
Locally fine, production always fails on TranscriptsDisabledException

### ISSUE THREAD

**Issue by edstevo** [MrMySQL/youtube-transcript#1]
Hi - this is working fine locally, but when on my production server it always fails with "TranscriptsDisabledException".

I've tried multiple video urls.

Do you have any ideas as to why this could be?

Thanks

**Comment by MrMySQL** [comment]
Hey! It’s probably that YouTube doesn’t recognizes the IP address of your productions as safe and asks for human verification. I was using proxy server for that for my AWS prod environment.

**Comment by edstevo** [comment]
Annoying but I've also reached that conclusion! 

Otherwise, a great bit of work. Thank you!
